num1 = int(input('Введите ваше первое число: '))
num2 = int(input('Введите ваше второе число: '))
print('Сумма: ' , num1 + num2)
print('Разность: ' , num1 - num2)
print('Произведение: ' , num1 * num2)
print('Деление: ' , num1 / num2)
print('Целая часть: ' , num1 // num2)
print('Остаток: ' , num1 % num2)
print('Степень: ' , num1 ** num2)